### ISSUE TITLE
Access rights to the repo

### ISSUE THREAD

**Issue by matuskalas** [elixir-europe/biohackathon-projects-2022#4]
Hey @martin-nc and all 😊

What is the idea with who has the rights to push and merge content of a project?

Is it the project leads, more participants, ...? Or are we encouraged to create another repo in another organisation and manage that ourselves?

Many thanks 🙏🏽

**Comment by martin-nc** [comment]
Hi Matúš,

The idea is that project leads should be able to merge PRs (but any 
project members can create PRs). Have you got the right permissions for 
your project?

Cheers
Martin

**Comment by matuskalas** [comment]
Thanks for your reply @martin-nc 🙏🏽

Ok, then with PRs in a repo like this, leads and followers will have to turn off notifications 😊

The wording of your reply makes me curious, is GitHub so fancy now that there could be access rights specified to the level of modifying a given path (folder, file)? 😮

I'm personally not a project lead, just an invitee of project 25. So PRs then, notifications off, fair enough👍🏽

**Comment by martin-nc** [comment]
@matuskalas sorry - I wasn't very clear! In reality people don't use these project folders to store code. They're pretty much there to store info about the project (in the README), so there are very few commits. Often people don't do any commits at all to the project folder, because they are working on existing projects that already have a home elsewhere, or that need to have a home elsewhere. You can check last year's project folders, for example: https://github.com/elixir-europe/biohackathon-projects-2021. I haven't found notifications troublesome because there aren't many!

So to answer part of you original question, which I'm afraid I inadvertently skipped, you can of course use these folders to store code, but it may make more sense long-term for you to store your project code in another repo. If it's an ELIXIR project then it could be another repo within the organisation. 

> is GitHub so fancy now that there could be access rights specified to the level of modifying a given path (folder, file)?

Not that I'm aware! If a project wanted to make lots of commits to the project folder we would have have to give the project lead elevated permission to the whole repo. I'm not sure if there is any other way. But as I said this hasn't been necessary in the past. People can create a PR for the occasional change to the README. 

Does that make sense?

**Comment by martin-nc** [comment]
@matuskalas Can I close this now?
